sudo: false
language: node_js
node_js:
- '12'
branches:
  only:
  - master
script: make travis
deploy:
- provider: script
  skip_cleanup: true
  script: bash ./scripts/publish.sh
  on:
    branch: master
    node_js: 12
env:
  global:
    - ALIYUN_ENDPOINT=http://39.98.93.191/admin
    - ALIYUN_ACCESS_KEY=z1aWXyf27QaUtAAT6wv4t5sL4visgBhRBPb
    # ALIYUN_ACCESS_SECRET
    - secure: SEOaO/gtaSRXVDWEfloCrrmqk6E3v3o67LkDkoz0fslmyFGObQY1nuFKYHf+Bcbi0bmgWci3FLiBp+iPekzp6QZD2KVcb1LOF2EIXRhQoQwgIEHef8nBGDx86AKVJpqRSMjICAvBNqPJtT0UHz1COMHF/gwVZxBzJ0fw6qvcAiyPDnczyjKGkU00okxDA5h28Fv0ab0fn2E3pKoLmJNnqWvL08FJo40PAF7ofUmT86rXQ4d2pegODslwBGoSDsZlBqI3+TYWXqonlTxums6u/U+BpO+ETLAmEDID2Vyi/0CEGbYyvIx5f5jTKhyvFXQqWHGaba53+yoEyAeu9oLpPHIzuhZx/TSIIFIgFWehtFmtSdFlyXvc1yjXkkapXs4LYJ6Jg4I58U1bbsXbMAm7lMkwtDNi5/U9ivB8aBwiYkLrVYAvBlA2wMWHtI6FuPpo/KW4nqjZ+l+nKPfjQt025LaFLbz9/cSq5jlb34cxIo3sP1j9ktYcRY1DQt5Xd00wSCOrcNJUIPMK6Lw+cNK5sKJz2nDYxY9l41+F2htfwQszJEATXHw+Z+oT1ErtwwgahTa90lQ9bMEmkkjGSTY6rH2Ae67apGzkMK+8k/sVdIWbdtKnt6vW57GLoRg416871tDHb/X0+6qnQBa70POAqvMFtsMJxaY9iIbVLu/YSX4=
    - AWS_ENDPOINT=http://54.213.55.12/admin
    - AWS_ACCESS_KEY=z1W9k2T7XTddPMtArMs7gs6pJYvsN63dggE
    # AWS_ACCESS_SECRET
    - secure: MFCs+MPFUlA0jkrQ0tzeB6+M0LL6lGEjrmFmqBVeHw6aAq/MDwWWgIj4fYObjW9HvFrGQsQRwQfpiApovUhKENGsFKEX2RINbDLeTE2KHIuU/RpzpUijTrP2yCo4zyZvlHsKdiSq80MD6Sy6t3q5l40Ahtc94pAcTEWacvv4qowpUlfbnM53ntMMUJt2j548hWkbiofZMzjUiL0zgRqU8IsJdw32QTeHvZfjMQ3HCfcd8Yds5/0qz7PvBkbcW6c6regkl37n0MtkZIxsRelrVMDgmRuNd/Lvjs19X/BuWsKqtF9NPqGfl1yaMpLzEfDyz/29YlIf0CMWFoXmTB7VGTaJdOZuUk8eX9r0qx5BHFIH9b8l/J63zAs3StcTiOmq3rIbOmy3i+/fWHW4VRtaXGxAYna5KMKspOcHRo4eDxe7o5+GUgmvJ9Kllal3BE3znUMPPirO0XhjVllyrVyqSCfnjUe4yTadexL70pg5yDBou7XKqzL/53S2hWr2/TRIPj4fDP2aZ2RVQprfwyrD/rgbuCdnkK7A3CCDX16nLplyTzQ2jHAXd9rp2JN0S2bm1wLv20rfWi13flhkDgd1fEb88GbW9lV6JKay/MRdKDq28C7ULgoV2Y4vY/kDq29bZCLb1S32+dmDfDCq5Q+MoMtzi1K77DXGHofUE2Cr25k=
    - secure: OH6OyExjBZE/C62nagGCRMqujbsAwjhawYKvfM/WVU0hXIsBvHBe4YR9r+6s2r9r2DQGS2C8jnirzglEoOYjClRQgvqgmeUjWGvHftUqyzdzs6tqTv0E616Lgq+AIUBeEKNZ9AMcXFtA8TvSDrzZelbHBlqPZa27Izv4A++zBrz4KJTk7k6s2lQOfOcko7HkFGJOXCONEGdLALFqluoX+9kVeUuyQi9Cz8d9Q+aMZnTIonaIGcCqzm2ezc6YazA8eLddeCJ22SI7BWgqqpiCOrEThzQzbbdTa/zw2EEkuEnEFbELdhczS0RjUumsSqx/5lhPhriWiIX+yOa4AeMQi3c4Sz70YonnrNa5jSfd9baOyrItvR/8Qf+9s2ktxpUYZzRG1EOVVtV3agkae1bY56Ssv6ui1sHMyWQBjkM/A03+HM/jJJuTX6vNOJfwOvbgv7UY4WIQlCDjpJggC4HEIi4m7rYUhqmv1q3yqriXiDAMhLx55Pt/HYboAKl7Qg1wZvZkuhnbR2Cpr4+d1u6BW+/8bmcxqC1QAuFBZyrxbwG3GP8S8plSCxQmvvga9QVjKuYh34I0eFPS1iyRm1FBgSzZG85ErOtBCuWed3ovKDANEBWZemj6odvkqW+qEgueHSH6E6ZSr+ZZNBBJfczUwBE4CuIQtCiNq0r9QSouGUk=
