sudo: false
language: node_js
node_js:
- '12'
branches:
  only:
  - master
script: make travis
deploy:
- provider: script
  skip_cleanup: true
  script: bash ./scripts/publish.sh
  on:
    branch: master
    node_js: 12
env:
  global:
    secure: OH6OyExjBZE/C62nagGCRMqujbsAwjhawYKvfM/WVU0hXIsBvHBe4YR9r+6s2r9r2DQGS2C8jnirzglEoOYjClRQgvqgmeUjWGvHftUqyzdzs6tqTv0E616Lgq+AIUBeEKNZ9AMcXFtA8TvSDrzZelbHBlqPZa27Izv4A++zBrz4KJTk7k6s2lQOfOcko7HkFGJOXCONEGdLALFqluoX+9kVeUuyQi9Cz8d9Q+aMZnTIonaIGcCqzm2ezc6YazA8eLddeCJ22SI7BWgqqpiCOrEThzQzbbdTa/zw2EEkuEnEFbELdhczS0RjUumsSqx/5lhPhriWiIX+yOa4AeMQi3c4Sz70YonnrNa5jSfd9baOyrItvR/8Qf+9s2ktxpUYZzRG1EOVVtV3agkae1bY56Ssv6ui1sHMyWQBjkM/A03+HM/jJJuTX6vNOJfwOvbgv7UY4WIQlCDjpJggC4HEIi4m7rYUhqmv1q3yqriXiDAMhLx55Pt/HYboAKl7Qg1wZvZkuhnbR2Cpr4+d1u6BW+/8bmcxqC1QAuFBZyrxbwG3GP8S8plSCxQmvvga9QVjKuYh34I0eFPS1iyRm1FBgSzZG85ErOtBCuWed3ovKDANEBWZemj6odvkqW+qEgueHSH6E6ZSr+ZZNBBJfczUwBE4CuIQtCiNq0r9QSouGUk=
