sudo: false
language: node_js
node_js:
- '12'
branches:
  only:
  - master
script: make travis
deploy:
- provider: script
  skip_cleanup: true
  script: bash ./scripts/publish.sh
  on:
    branch: master
    node_js: 12
env:
  global:
    - ALIYUN_ENDPOINT=http://39.98.93.191/admin
    - ALIYUN_ACCESS_KEY=z1RhdnPRJ6mxN8u6SaPqLvRj9Pm7JdABi1U
    # ALIYUN_ACCESS_SECRET
    - secure: dZXR/XuehnchYenxoizzXW0Pbct8EDJoBPIwoJWj+OogwszBg1wirMGLku5xFisA+JdqoM4RmbQ65mflYH9Z9OcOnMQiYlZ1Xnq+ulb5e5tm3va+NlNUsX1q4/Ex4tZ1Uy5LTvp9Rv2lXezF7wAJuupRLLqrFt92GejXjUzRpMwewLJdc4TUfhxS4Bd7b4hTuFecN1QzO2fk47H+T3aPYQiPYh1IyJt3kT/tAzDnIosokbJOqaGKpmRrXAM0wAxTlQs4BDGIZP9i5AC8CZmh++eHViQG+rBI2Z4oqQfgn3SSUqngtxo7JZVfwTq7RGBmv0hSTtqLzg6Jk39tCN5M0LUsGIykI+KfJSlIHTonSi7hK7pWDwbYQcU391Bf2odVk1Sb8VJ0YPnt3TSatu+hQpdvnlU92rhyGUwLO/d/gwB7pFm9JA1ARBWMQA/O08gDWsA3ePHxVa1jugmgbJICb/BOS1lrT68LmWUWEuqr+bQoMCNkYBsyCpAzUcx+bRkmI831LCleWB5xFgAg310QB+YBVo90Rg6XHrmh11EqPW4vEfZpxTUbgGMhcHt9IKZq0+1vjx8cL2O3ssG+nTUAM7uPIFEO1NBBjGXWIfSA+ECi6N70159iLzXYQbFSftx+JTKcFiK6SLHVe0ePNLXHJAJQhi5LAjsEmmUn1tS8i/Q=
    - AWS_ENDPOINT=http://54.213.55.12/admin
    - AWS_ACCESS_KEY=z1W9k2T7XTddPMtArMs7gs6pJYvsN63dggE
    # AWS_ACCESS_SECRET
    - secure: MFCs+MPFUlA0jkrQ0tzeB6+M0LL6lGEjrmFmqBVeHw6aAq/MDwWWgIj4fYObjW9HvFrGQsQRwQfpiApovUhKENGsFKEX2RINbDLeTE2KHIuU/RpzpUijTrP2yCo4zyZvlHsKdiSq80MD6Sy6t3q5l40Ahtc94pAcTEWacvv4qowpUlfbnM53ntMMUJt2j548hWkbiofZMzjUiL0zgRqU8IsJdw32QTeHvZfjMQ3HCfcd8Yds5/0qz7PvBkbcW6c6regkl37n0MtkZIxsRelrVMDgmRuNd/Lvjs19X/BuWsKqtF9NPqGfl1yaMpLzEfDyz/29YlIf0CMWFoXmTB7VGTaJdOZuUk8eX9r0qx5BHFIH9b8l/J63zAs3StcTiOmq3rIbOmy3i+/fWHW4VRtaXGxAYna5KMKspOcHRo4eDxe7o5+GUgmvJ9Kllal3BE3znUMPPirO0XhjVllyrVyqSCfnjUe4yTadexL70pg5yDBou7XKqzL/53S2hWr2/TRIPj4fDP2aZ2RVQprfwyrD/rgbuCdnkK7A3CCDX16nLplyTzQ2jHAXd9rp2JN0S2bm1wLv20rfWi13flhkDgd1fEb88GbW9lV6JKay/MRdKDq28C7ULgoV2Y4vY/kDq29bZCLb1S32+dmDfDCq5Q+MoMtzi1K77DXGHofUE2Cr25k=
    - secure: OH6OyExjBZE/C62nagGCRMqujbsAwjhawYKvfM/WVU0hXIsBvHBe4YR9r+6s2r9r2DQGS2C8jnirzglEoOYjClRQgvqgmeUjWGvHftUqyzdzs6tqTv0E616Lgq+AIUBeEKNZ9AMcXFtA8TvSDrzZelbHBlqPZa27Izv4A++zBrz4KJTk7k6s2lQOfOcko7HkFGJOXCONEGdLALFqluoX+9kVeUuyQi9Cz8d9Q+aMZnTIonaIGcCqzm2ezc6YazA8eLddeCJ22SI7BWgqqpiCOrEThzQzbbdTa/zw2EEkuEnEFbELdhczS0RjUumsSqx/5lhPhriWiIX+yOa4AeMQi3c4Sz70YonnrNa5jSfd9baOyrItvR/8Qf+9s2ktxpUYZzRG1EOVVtV3agkae1bY56Ssv6ui1sHMyWQBjkM/A03+HM/jJJuTX6vNOJfwOvbgv7UY4WIQlCDjpJggC4HEIi4m7rYUhqmv1q3yqriXiDAMhLx55Pt/HYboAKl7Qg1wZvZkuhnbR2Cpr4+d1u6BW+/8bmcxqC1QAuFBZyrxbwG3GP8S8plSCxQmvvga9QVjKuYh34I0eFPS1iyRm1FBgSzZG85ErOtBCuWed3ovKDANEBWZemj6odvkqW+qEgueHSH6E6ZSr+ZZNBBJfczUwBE4CuIQtCiNq0r9QSouGUk=
