name: Blocklet

on:
  push:
    branches:
      - main

jobs:
  Deploy:

    runs-on: ubuntu-latest

    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Test
      run: make github-action-test

    - name: Deploy
      env:
        AWS_NODE_ENDPOINT: ${{ secrets.STAGING_NODE_ENDPOINT }}
        AWS_NODE_ACCESS_KEY: ${{ secrets.STAGING_NODE_ACCESS_KEY }}
        AWS_NODE_ACCESS_SECRET: ${{ secrets.STAGING_NODE_ACCESS_SECRET }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        STAGING_REGISTRY: ${{ secrets.STAGING_REGISTRY }}
        ABTNODE_DEV_STAGING_SK: ${{ secrets.ABTNODE_DEV_STAGING_SK }}
      run: bash ./scripts/publish.sh

    - name: Release to Github
      uses: blocklet/action-release-to-github@v1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
